//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineOrder
    {
        public int CountOrder { get; set; }
        public string PurchasePrice { get; set; }
        public Nullable<int> CountShipment { get; set; }
        public int CodTovara_FK_ { get; set; }
        public int NumberOrder_FK_ { get; set; }
        public Nullable<System.DateTime> DataManuf { get; set; }
        public int ID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
