//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.LineOrder = new HashSet<LineOrder>();
        }
    
        public int Number { get; set; }
        public System.DateTime DataOrder { get; set; }
        public Nullable<System.DateTime> DataShipment { get; set; }
        public string StatusOrder { get; set; }
        public string NameOrganizationPostavshik_FK_ { get; set; }
        public string FIOworker_FK_ { get; set; }
    
        public virtual Worker Worker { get; set; }
        public virtual Postavshik Postavshik { get; set; }
        public virtual Worker Worker1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineOrder> LineOrder { get; set; }
    }
}
